baseURL = "https://www.amartabakovic.ch/"
languageCode = "us-en"
title = "Amar Tabakovic"
theme = "amar-theme"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Amar Tabakovic"
  github = "https://github.com/amartabakovic"
  sitename = "Amar Tabakovic"
  twitter = "@AmarrrrrT"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
#    style = "native"
    style = "rrt"
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
 
   
    
  