baseURL = "https://www.amartabakovic.ch/"
languageCode = "us-en"
title = "Amar Tabakovic"
description = "Personal site of Amar Tabakovic."
theme = "amar-theme"

disableKinds = ["taxonomyTerm"]

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[Taxonomies]
  category = "categories"

[Author]  
  name = "Amar Tabakovic"

[params]
  author = "Amar Tabakovic"
  github = "https://github.com/amartabakovic"
  sitename = "Amar Tabakovic"
  twitter = "@AmarrrrrT"
  description = "Personal site of Amar Tabakovic."
  images = ["static/favicon.png"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "rrt"
    tabWidth = 4


 
   
    
  