baseURL = "http://www.amartabakovic.ch/"
languageCode = "us-en"
title = "Amar Tabakovic"
theme = "amar-theme"

 [menu]
   [[menu.main]]
    name = "Projects"
    pre = "pen-tool"
    url = "/projects/"
    weight = 1
   [[menu.main]]
    name = "Blog"
    pre = "pen-tool"
    url = "/blog/"
    weight = 2
   [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 3
 
   
    
  